# Generated by Django 5.1.3 on 2024-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('ngo', 'NGO'), ('hospital', 'Hospital'), ('other', 'Other')], max_length=20)),
                ('organization_name', models.CharField(max_length=100)),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_mobile', models.CharField(max_length=15)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('co_organizer_name', models.CharField(blank=True, max_length=100)),
                ('co_organizer_mobile', models.CharField(blank=True, max_length=15)),
                ('camp_name', models.CharField(max_length=100)),
                ('camp_address', models.TextField()),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh')], max_length=2)),
                ('district', models.CharField(choices=[('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor')], max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('bloodbank', models.CharField(choices=[('bb1', 'BloodBank 1'), ('bb2', 'BloodBank 2')], max_length=20)),
                ('camp_propose_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('estimated_participants', models.IntegerField()),
            ],
        ),
    ]
